source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'will_paginate'
gem 'formtastic'
gem 'nifty-generators'
gem "mocha", :group => :test
gem "bcrypt-ruby", :require => "bcrypt"
gem "wirble"
gem "hirb"

group :test do
  gem 'shoulda'
  gem 'factory_girl_rails'
end