source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'will_paginate'
gem 'nifty-generators'
gem 'validates_timeliness', '~> 3.0.2'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'chronic'

group :development do
  gem 'wirble'
	gem 'hirb'
	gem 'populator3'
	gem 'faker'
end

group :test do
	gem 'shoulda'
	gem 'factory_girl_rails'
	gem 'mocha'
	gem 'cucumber-rails'
	gem 'capybara'
	gem 'database_cleaner'
	gem 'launchy'
	gem 'simplecov'
end
